[package]
name = "foxbox-adapter-xbee-example"
version = "0.1.0"
authors = ["David Scravaglieri <david@scravaglieri.net>"]

[dependencies]
clippy = "0.0.48"
libc="0.2.8"
va_list = "0.0.3"
"xbee" = { git = "https://github.com/fxbox/libxbee-rust.git" }

